//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIC.CoreType.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIC.CoreType.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高警.
        /// </summary>
        public static string AlarmGrade_HighAlert {
            get {
                return ResourceManager.GetString("AlarmGrade_HighAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高危.
        /// </summary>
        public static string AlarmGrade_HighDanger {
            get {
                return ResourceManager.GetString("AlarmGrade_HighDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高正常.
        /// </summary>
        public static string AlarmGrade_HighNormal {
            get {
                return ResourceManager.GetString("AlarmGrade_HighNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无效.
        /// </summary>
        public static string AlarmGrade_Invalid {
            get {
                return ResourceManager.GetString("AlarmGrade_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低警.
        /// </summary>
        public static string AlarmGrade_LowAlert {
            get {
                return ResourceManager.GetString("AlarmGrade_LowAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低危.
        /// </summary>
        public static string AlarmGrade_LowDanger {
            get {
                return ResourceManager.GetString("AlarmGrade_LowDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低正常.
        /// </summary>
        public static string AlarmGrade_LowNormal {
            get {
                return ResourceManager.GetString("AlarmGrade_LowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有.
        /// </summary>
        public static string AlarmGradeFilter_All {
            get {
                return ResourceManager.GetString("AlarmGradeFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 危险.
        /// </summary>
        public static string AlarmGradeFilter_Danger {
            get {
                return ResourceManager.GetString("AlarmGradeFilter_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常.
        /// </summary>
        public static string AlarmGradeFilter_Normal {
            get {
                return ResourceManager.GetString("AlarmGradeFilter_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string AlarmGradeFilter_Warning {
            get {
                return ResourceManager.GetString("AlarmGradeFilter_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告与危险.
        /// </summary>
        public static string AlarmGradeFilter_WarningAndDanger {
            get {
                return ResourceManager.GetString("AlarmGradeFilter_WarningAndDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位机控制.
        /// </summary>
        public static string AlarmSaveStr_HostComputer {
            get {
                return ResourceManager.GetString("AlarmSaveStr_HostComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实时传递.
        /// </summary>
        public static string AlarmSaveStr_RealTime {
            get {
                return ResourceManager.GetString("AlarmSaveStr_RealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 危险.
        /// </summary>
        public static string AlarmStrategt_Danger {
            get {
                return ResourceManager.GetString("AlarmStrategt_Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常.
        /// </summary>
        public static string AlarmStrategt_Normal {
            get {
                return ResourceManager.GetString("AlarmStrategt_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        public static string AlarmStrategt_Warning {
            get {
                return ResourceManager.GetString("AlarmStrategt_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string AMP_Auto {
            get {
                return ResourceManager.GetString("AMP_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string AMP_Five {
            get {
                return ResourceManager.GetString("AMP_Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string AMP_One {
            get {
                return ResourceManager.GetString("AMP_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string AMP_Ten {
            get {
                return ResourceManager.GetString("AMP_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string AMP_Two {
            get {
                return ResourceManager.GetString("AMP_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加速度.
        /// </summary>
        public static string AVS_Acceleration {
            get {
                return ResourceManager.GetString("AVS_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位移.
        /// </summary>
        public static string AVS_Displacement {
            get {
                return ResourceManager.GetString("AVS_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        public static string AVS_Speed {
            get {
                return ResourceManager.GetString("AVS_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string CollectionChangedAction_Add {
            get {
                return ResourceManager.GetString("CollectionChangedAction_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移除.
        /// </summary>
        public static string CollectionChangedAction_Remove {
            get {
                return ResourceManager.GetString("CollectionChangedAction_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 硬件.
        /// </summary>
        public static string ComputeHost_Hardware {
            get {
                return ResourceManager.GetString("ComputeHost_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件.
        /// </summary>
        public static string ComputeHost_Software {
            get {
                return ResourceManager.GetString("ComputeHost_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波德.
        /// </summary>
        public static string CurveType_Bode {
            get {
                return ResourceManager.GetString("CurveType_Bode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双通道耦合.
        /// </summary>
        public static string CurveType_DoubleCoupling {
            get {
                return ResourceManager.GetString("CurveType_DoubleCoupling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奈奎斯特.
        /// </summary>
        public static string CurveType_Nyquist {
            get {
                return ResourceManager.GetString("CurveType_Nyquist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转速三位谱.
        /// </summary>
        public static string CurveType_RPM3D {
            get {
                return ResourceManager.GetString("CurveType_RPM3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单通道瞬态.
        /// </summary>
        public static string CurveType_SignalTransient {
            get {
                return ResourceManager.GetString("CurveType_SignalTransient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单通道连续.
        /// </summary>
        public static string CurveType_SingleContinuous {
            get {
                return ResourceManager.GetString("CurveType_SingleContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间三维谱.
        /// </summary>
        public static string CurveType_Time3D {
            get {
                return ResourceManager.GetString("CurveType_Time3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 能量.
        /// </summary>
        public static string DiagnosisMethod_Energy {
            get {
                return ResourceManager.GetString("DiagnosisMethod_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 频率峰值.
        /// </summary>
        public static string DiagnosisMethod_FrequencyPeakValue {
            get {
                return ResourceManager.GetString("DiagnosisMethod_FrequencyPeakValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        public static string DigitalUnit_RPM {
            get {
                return ResourceManager.GetString("DigitalUnit_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户定义.
        /// </summary>
        public static string DivFreType_Custom {
            get {
                return ResourceManager.GetString("DivFreType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基于范围.
        /// </summary>
        public static string DivFreType_Range {
            get {
                return ResourceManager.GetString("DivFreType_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基于转速.
        /// </summary>
        public static string DivFreType_RPM {
            get {
                return ResourceManager.GetString("DivFreType_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 带通.
        /// </summary>
        public static string FilterType_BandPass {
            get {
                return ResourceManager.GetString("FilterType_BandPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高通.
        /// </summary>
        public static string FilterType_HighPass {
            get {
                return ResourceManager.GetString("FilterType_HighPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低通.
        /// </summary>
        public static string FilterType_LowPass {
            get {
                return ResourceManager.GetString("FilterType_LowPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400Hz.
        /// </summary>
        public static string HP_FourHundred {
            get {
                return ResourceManager.GetString("HP_FourHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不加高通.
        /// </summary>
        public static string HP_Not {
            get {
                return ResourceManager.GetString("HP_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000Hz.
        /// </summary>
        public static string HP_OneThousand {
            get {
                return ResourceManager.GetString("HP_OneThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10Hz.
        /// </summary>
        public static string HP_Ten {
            get {
                return ResourceManager.GetString("HP_Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加速度.
        /// </summary>
        public static string InSignalCategory_Acceleration {
            get {
                return ResourceManager.GetString("InSignalCategory_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缓存.
        /// </summary>
        public static string InSignalCategory_Cach {
            get {
                return ResourceManager.GetString("InSignalCategory_Cach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位移.
        /// </summary>
        public static string InSignalCategory_Displacement {
            get {
                return ResourceManager.GetString("InSignalCategory_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        public static string InSignalCategory_Speed {
            get {
                return ResourceManager.GetString("InSignalCategory_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不积分.
        /// </summary>
        public static string Integration_None {
            get {
                return ResourceManager.GetString("Integration_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一次积分.
        /// </summary>
        public static string Integration_One {
            get {
                return ResourceManager.GetString("Integration_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二次积分.
        /// </summary>
        public static string Integration_Two {
            get {
                return ResourceManager.GetString("Integration_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附加.
        /// </summary>
        public static string NaturalFreMode_Additive {
            get {
                return ResourceManager.GetString("NaturalFreMode_Additive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排除.
        /// </summary>
        public static string NaturalFreMode_Subtractive {
            get {
                return ResourceManager.GetString("NaturalFreMode_Subtractive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIC9800.
        /// </summary>
        public static string nType_Four {
            get {
                return ResourceManager.GetString("nType_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIC3600.
        /// </summary>
        public static string nType_One {
            get {
                return ResourceManager.GetString("nType_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIC1360.
        /// </summary>
        public static string nType_Three {
            get {
                return ResourceManager.GetString("nType_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIC8600.
        /// </summary>
        public static string nType_Two {
            get {
                return ResourceManager.GetString("nType_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIC9900.
        /// </summary>
        public static string nType_Zero {
            get {
                return ResourceManager.GetString("nType_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大最小绝对值取样.
        /// </summary>
        public static string QueryCompressType_MaxAndMin_Absolute {
            get {
                return ResourceManager.GetString("QueryCompressType_MaxAndMin_Absolute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大最小取样.
        /// </summary>
        public static string QueryCompressType_MaxAndMin_Normal {
            get {
                return ResourceManager.GetString("QueryCompressType_MaxAndMin_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顺序取样.
        /// </summary>
        public static string QueryCompressType_Sequence {
            get {
                return ResourceManager.GetString("QueryCompressType_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string RunningMode_Auto {
            get {
                return ResourceManager.GetString("RunningMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动.
        /// </summary>
        public static string RunningMode_Manual {
            get {
                return ResourceManager.GetString("RunningMode_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平稳运行.
        /// </summary>
        public static string RunningState_Stable {
            get {
                return ResourceManager.GetString("RunningState_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启机.
        /// </summary>
        public static string RunningState_Start {
            get {
                return ResourceManager.GetString("RunningState_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停机.
        /// </summary>
        public static string RunningState_Stop {
            get {
                return ResourceManager.GetString("RunningState_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连续.
        /// </summary>
        public static string SampleType_Continuous {
            get {
                return ResourceManager.GetString("SampleType_Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周期.
        /// </summary>
        public static string SampleType_Cycle {
            get {
                return ResourceManager.GetString("SampleType_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瞬态.
        /// </summary>
        public static string SampleType_Transient {
            get {
                return ResourceManager.GetString("SampleType_Transient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加速度.
        /// </summary>
        public static string SensorType_Acceleration {
            get {
                return ResourceManager.GetString("SensorType_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位移.
        /// </summary>
        public static string SensorType_Displacement {
            get {
                return ResourceManager.GetString("SensorType_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速度.
        /// </summary>
        public static string SensorType_Speed {
            get {
                return ResourceManager.GetString("SensorType_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 维护模式.
        /// </summary>
        public static string ServerStatusType_Maintenance {
            get {
                return ResourceManager.GetString("ServerStatusType_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线模式.
        /// </summary>
        public static string ServerStatusType_Online {
            get {
                return ResourceManager.GetString("ServerStatusType_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报警点趋势.
        /// </summary>
        public static string SignalDisplayType_AlarmPointTrend {
            get {
                return ResourceManager.GetString("SignalDisplayType_AlarmPointTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 趋势.
        /// </summary>
        public static string SignalDisplayType_AMSTrend {
            get {
                return ResourceManager.GetString("SignalDisplayType_AMSTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伯德.
        /// </summary>
        public static string SignalDisplayType_Bode {
            get {
                return ResourceManager.GetString("SignalDisplayType_Bode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 频域.
        /// </summary>
        public static string SignalDisplayType_FrequencyDomain {
            get {
                return ResourceManager.GetString("SignalDisplayType_FrequencyDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分频报警.
        /// </summary>
        public static string SignalDisplayType_MultiDivFre {
            get {
                return ResourceManager.GetString("SignalDisplayType_MultiDivFre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 奈圭斯特.
        /// </summary>
        public static string SignalDisplayType_Nyquist {
            get {
                return ResourceManager.GetString("SignalDisplayType_Nyquist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 变工况.
        /// </summary>
        public static string SignalDisplayType_OffDesignCondition {
            get {
                return ResourceManager.GetString("SignalDisplayType_OffDesignCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阶次分析.
        /// </summary>
        public static string SignalDisplayType_OrderAnalysis {
            get {
                return ResourceManager.GetString("SignalDisplayType_OrderAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轴心轨迹.
        /// </summary>
        public static string SignalDisplayType_Ortho {
            get {
                return ResourceManager.GetString("SignalDisplayType_Ortho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转速三维谱.
        /// </summary>
        public static string SignalDisplayType_RPM3D {
            get {
                return ResourceManager.GetString("SignalDisplayType_RPM3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单一分频报警.
        /// </summary>
        public static string SignalDisplayType_SingleDivFre {
            get {
                return ResourceManager.GetString("SignalDisplayType_SingleDivFre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间三维谱.
        /// </summary>
        public static string SignalDisplayType_Time3DSpectrum {
            get {
                return ResourceManager.GetString("SignalDisplayType_Time3DSpectrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时域.
        /// </summary>
        public static string SignalDisplayType_TimeDomain {
            get {
                return ResourceManager.GetString("SignalDisplayType_TimeDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数值.
        /// </summary>
        public static string SignalDisplayType_Value {
            get {
                return ResourceManager.GetString("SignalDisplayType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模拟.
        /// </summary>
        public static string SignalType_Analog {
            get {
                return ResourceManager.GetString("SignalType_Analog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数字.
        /// </summary>
        public static string SignalType_Digital {
            get {
                return ResourceManager.GetString("SignalType_Digital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 振动.
        /// </summary>
        public static string SignalType_Vibration {
            get {
                return ResourceManager.GetString("SignalType_Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轴位移.
        /// </summary>
        public static string SVType_AxialTranslation {
            get {
                return ResourceManager.GetString("SVType_AxialTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 峰值.
        /// </summary>
        public static string SVType_Peak {
            get {
                return ResourceManager.GetString("SVType_Peak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 峰峰值.
        /// </summary>
        public static string SVType_PeakToPeak {
            get {
                return ResourceManager.GetString("SVType_PeakToPeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效值.
        /// </summary>
        public static string SVType_RMS {
            get {
                return ResourceManager.GetString("SVType_RMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转速.
        /// </summary>
        public static string SVType_RPM {
            get {
                return ResourceManager.GetString("SVType_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动.
        /// </summary>
        public static string ThresholdMode_Auto {
            get {
                return ResourceManager.GetString("ThresholdMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动.
        /// </summary>
        public static string ThresholdMode_Manual {
            get {
                return ResourceManager.GetString("ThresholdMode_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不启用.
        /// </summary>
        public static string ThresholdMode_None {
            get {
                return ResourceManager.GetString("ThresholdMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等角度转速触发.
        /// </summary>
        public static string TriggerType_Angle {
            get {
                return ResourceManager.GetString("TriggerType_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自由触发.
        /// </summary>
        public static string TriggerType_Auto {
            get {
                return ResourceManager.GetString("TriggerType_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等周期触发.
        /// </summary>
        public static string TriggerType_Cycle {
            get {
                return ResourceManager.GetString("TriggerType_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转速触发.
        /// </summary>
        public static string TriggerType_RPM {
            get {
                return ResourceManager.GetString("TriggerType_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s^2.
        /// </summary>
        public static string Unit_Acceleration {
            get {
                return ResourceManager.GetString("Unit_Acceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to um.
        /// </summary>
        public static string Unit_Displacement {
            get {
                return ResourceManager.GetString("Unit_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa.
        /// </summary>
        public static string Unit_Pressure {
            get {
                return ResourceManager.GetString("Unit_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        public static string Unit_RPM {
            get {
                return ResourceManager.GetString("Unit_RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string Unit_Tempature {
            get {
                return ResourceManager.GetString("Unit_Tempature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit_Unit {
            get {
                return ResourceManager.GetString("Unit_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/s.
        /// </summary>
        public static string Unit_Velocity {
            get {
                return ResourceManager.GetString("Unit_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员.
        /// </summary>
        public static string UserLevels_Administrator {
            get {
                return ResourceManager.GetString("UserLevels_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程师.
        /// </summary>
        public static string UserLevels_Engineer {
            get {
                return ResourceManager.GetString("UserLevels_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位机连续波形.
        /// </summary>
        public static string VAlarmSaveStr_HostContinuousWave {
            get {
                return ResourceManager.GetString("VAlarmSaveStr_HostContinuousWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位机间隔点值.
        /// </summary>
        public static string VAlarmSaveStr_HostIntervalPoint {
            get {
                return ResourceManager.GetString("VAlarmSaveStr_HostIntervalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位机间隔瞬态波形.
        /// </summary>
        public static string VAlarmSaveStr_HostIntervalWave {
            get {
                return ResourceManager.GetString("VAlarmSaveStr_HostIntervalWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位机非间隔点值.
        /// </summary>
        public static string VAlarmSaveStr_HostNotIntervalPoint {
            get {
                return ResourceManager.GetString("VAlarmSaveStr_HostNotIntervalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上位机非间隔瞬态波形.
        /// </summary>
        public static string VAlarmSaveStr_HostNotIntervalWave {
            get {
                return ResourceManager.GetString("VAlarmSaveStr_HostNotIntervalWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下位机上传.
        /// </summary>
        public static string VAlarmSaveStr_LM {
            get {
                return ResourceManager.GetString("VAlarmSaveStr_LM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 布莱克曼窗.
        /// </summary>
        public static string Winfun_Blackman {
            get {
                return ResourceManager.GetString("Winfun_Blackman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海宁窗.
        /// </summary>
        public static string Winfun_Haining {
            get {
                return ResourceManager.GetString("Winfun_Haining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海明窗.
        /// </summary>
        public static string Winfun_Hamming {
            get {
                return ResourceManager.GetString("Winfun_Hamming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不加窗.
        /// </summary>
        public static string Winfun_None {
            get {
                return ResourceManager.GetString("Winfun_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三角窗.
        /// </summary>
        public static string Winfun_Triangle {
            get {
                return ResourceManager.GetString("Winfun_Triangle", resourceCulture);
            }
        }
    }
}
